sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install @angular/cli angular-cli-ghpages

script:
  - ng test
  - ng build --prod
  - ngh
